version: '3.7'
services:

    calculator-js-nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/app